/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthRecoverRouteImport } from './routes/auth.recover'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as TournamentsIdCheckinRouteImport } from './routes/tournaments.$id.checkin'
import { Route as TournamentsIdBracketRouteImport } from './routes/tournaments.$id.bracket'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/auth/recover',
  path: '/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdCheckinRoute = TournamentsIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => TournamentsIdRoute,
} as any)
const TournamentsIdBracketRoute = TournamentsIdBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => TournamentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/shop/$id': typeof ShopIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/checkin': typeof TournamentsIdCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/shop/$id': typeof ShopIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/checkin': typeof TournamentsIdCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/shop/$id': typeof ShopIdRoute
  '/tournaments/$id': typeof TournamentsIdRouteWithChildren
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/bracket': typeof TournamentsIdBracketRoute
  '/tournaments/$id/checkin': typeof TournamentsIdCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/community'
    | '/profile'
    | '/ranking'
    | '/shop'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/register'
    | '/profile/settings'
    | '/shop/$id'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/community'
    | '/profile'
    | '/ranking'
    | '/shop'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/register'
    | '/profile/settings'
    | '/shop/$id'
    | '/tournaments/$id'
    | '/tournaments'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/checkin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/community'
    | '/profile'
    | '/ranking'
    | '/shop'
    | '/auth/login'
    | '/auth/recover'
    | '/auth/register'
    | '/profile/settings'
    | '/shop/$id'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/tournaments/$id/bracket'
    | '/tournaments/$id/checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RankingRoute: typeof RankingRoute
  ShopRoute: typeof ShopRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  TournamentsIdRoute: typeof TournamentsIdRouteWithChildren
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/auth/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/checkin': {
      id: '/tournaments/$id/checkin'
      path: '/checkin'
      fullPath: '/tournaments/$id/checkin'
      preLoaderRoute: typeof TournamentsIdCheckinRouteImport
      parentRoute: typeof TournamentsIdRoute
    }
    '/tournaments/$id/bracket': {
      id: '/tournaments/$id/bracket'
      path: '/bracket'
      fullPath: '/tournaments/$id/bracket'
      preLoaderRoute: typeof TournamentsIdBracketRouteImport
      parentRoute: typeof TournamentsIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileSettingsRoute: typeof ProfileSettingsRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSettingsRoute: ProfileSettingsRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ShopRouteChildren {
  ShopIdRoute: typeof ShopIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIdRoute: ShopIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface TournamentsIdRouteChildren {
  TournamentsIdBracketRoute: typeof TournamentsIdBracketRoute
  TournamentsIdCheckinRoute: typeof TournamentsIdCheckinRoute
}

const TournamentsIdRouteChildren: TournamentsIdRouteChildren = {
  TournamentsIdBracketRoute: TournamentsIdBracketRoute,
  TournamentsIdCheckinRoute: TournamentsIdCheckinRoute,
}

const TournamentsIdRouteWithChildren = TournamentsIdRoute._addFileChildren(
  TournamentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RankingRoute: RankingRoute,
  ShopRoute: ShopRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  TournamentsIdRoute: TournamentsIdRouteWithChildren,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
